global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]

  - job_name: "keycloak-postgres"
    static_configs:
      - targets: ["keycloak-postgres-exporter:9187"]
